# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.18
jobs:
  build_project:
    working_directory: ~/app
    docker:
      - image: circleci/openjdk:8-jdk
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run: gradle dependencies
      - run: gradle bootJar
      - run: pwd
      - run: ls
      - persist_to_workspace: 
          root: ~/
          paths:
            - .

  deploy_project:
    executor: aws-cli/default
    steps:
      - attach_workspace: 
          at: ~/
      - aws-cli/setup:
          profile-name: default
      - run:
           pwd
      - run:
           ls /home/circleci/app
      - run:
          name: Update to S3
          command: aws  s3 sync /home/circleci/app/build/libs/simplerestuser-0.0.1-SNAPSHOT.jar s3://circleci-simplespring/ --delete

workflows:
  version: 2
  build:
    jobs:
      - build_project
      - deploy_project:
          requires:
            - build_project
          context: personal_aws