# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.18
jobs:
  build_project:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: gradle dependencies

      # run tests!
      - run: gradle bootJar
  deploy_project:
    executor: aws-cli/default
    steps:
      - attach_workspace:
          at: ~/repo
      - aws-cli/setup:
          profile-name: default
      - run:
          name: Update to S3
          command: aws  s3 sync ~/repo/simplespringboot/build/libs/simplerestuser-0.0.1-SNAPSHOT.jar s3://circleci-simplespring/ --deploy

workflows:
  version: 2
  build:
    jobs:
      - build_project
      - deploy_project:
          requires:
            - build_project
          context: personal_aws